ALTER TABLE `paper` ADD COLUMN description VARCHAR(128);
ALTER TABLE `paper` ADD COLUMN createTime VARCHAR(128);
ALTER TABLE `paper` ADD COLUMN isDistribution TINYINT(1);
ALTER TABLE `paper` ADD COLUMN programId INTEGER;
